version: '3.8'

services:
  app:
    image: home-library-app
    build: .
    container_name: hls-app
    restart: always
    env_file: .env
    environment:
      - DB_HOST=db
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - hls-network
    volumes:
      - ./src:/app/src

  db:
    image: postgres:alpine
    container_name: hls-db
    restart: always
    networks:
      - hls-network
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: postgres -c logging_collector=on -c log_statement=all

networks:
  hls-network:
    driver: bridge
volumes:
  dbdata:
